apiVersion: v2
name: alloy-loki-stack
description: Alloy + Loki stack with S3 storage
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: alloy
    version: "*"
    repository: https://grafana.github.io/helm-charts