apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.loki.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.loki.storage.size }}