apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.loki.s3.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.loki.s3.secretKey }}